### ISSUE TITLE
コントローラとアクションの作成

### ISSUE THREAD

**Issue by ahnjy-f** [ahnjy-f/prj_ruby#11]
修正中

**Comment by minaTsuruta** [comment]
担当します。

**Comment by dlehddus1285** [comment]
> 担当 し ま す。
作る時に route　ファイルみたらわかるんですけど
最初にはですね　indexの　コントローラーに入りますよね？
でも　初期ページは　ログインページなので　sessionにしなきゃいけないから

一応私は　こういう風に作って routeを通して　行く風にしました
もしよければ　参考してください

class Account::TopController < Account::Base
    def index
        if current_account
            render action: "dashborad"
        else
            redirect_to:"account_login"
        end
    end
end
