### ISSUE TITLE
app/views/account/top/dashborad

### ISSUE THREAD

**Issue by dlehddus1285** [ahnjy-f/prj_ruby#41]
dashboradを作って欲しいです

**Comment by ahnjy-f** [comment]
先私も指摘されていますけど、どの内容で、どこに必要なのか指定してください。

**Comment by dlehddus1285** [comment]
dashboradは　ログインをしたら　現れて　つまり　ログインが済んだら　dashboradに行きます
ログインしなかった場合には　ログインページになります
