### ISSUE TITLE
管理者一覧に行くためのメニュー項目の追加

### ISSUE THREAD

**Issue by bjson05** [ahnjy-f/prj_ruby#90]
管理者でログインする場合ではメニューに管理者一覧という項目を追加してこのページに入る状態にしたいです。

**Comment by minaTsuruta** [comment]
ドンさんがindex.html.erbに入れていたものを_header.html.erbにも取り込んでみます

**Comment by minaTsuruta** [comment]
#102 の動き(accountとmemberの情報？？？)がないとエラーになるみたいなので、#102が実装できてからpushします。

**Comment by dlehddus1285** [comment]
作りました
